{
    'name': 'Omni Referral Base',
    'version': '19.0.1.0.0',
    'summary': 'Module for Multi-Level Referral Network.',
    'description': 'Core module for multi-tier referral network and sales commission.',
    'category': 'Sales/Sales',
    'author': 'Sel Studio',
    'website': 'https://selstudio.id',
    'depends': ['base', 'sale', 'mail'],
    'license': 'LGPL-3',
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'views/commission_rule_views.xml',
        'views/member_views.xml',
        'views/commission_views.xml',
        'views/sale_order_views.xml',
        'views/res_config_settings_views.xml',
        'views/res_partner_views.xml',
        'views/menu.xml',
        'reports/member_card_report.xml',
    ],
    'images': ['static/description/banner.png'],
    'installable': True,
    'application': True, 
}