from odoo import fields, models


class ResConfigSettings(models.TransientModel):
    _inherit = "res.config.settings"

    referral_member_code_prefix = fields.Char(
        string="Member Code Prefix",
        config_parameter="omni_referral_base.referral_member_code_prefix",
        default="MEM",
        help="Prefix for autogenerated Member Code sequence.",
    )
     # ── Commission Settings ──────────────────────────────────────────
    referral_auto_approve_active_upline = fields.Boolean(
        string="Auto-Approve Commission for Active Upline",
        config_parameter="omni_referral_base.auto_approve_active_upline",
        default=True,
        help="If enabled, commission is automatically approved when the upline "
             "has at least one confirmed Sales Order in the past month.",
    )
    referral_skip_inactive_upline = fields.Boolean(
        string="Skip Commission for Inactive Upline",
        config_parameter="omni_referral_base.skip_inactive_upline",
        default=False,
        help="If enabled, commission is NOT created for uplines who have no confirmed "
             "Sales Order in the past month. If disabled, commission is created but stays Pending.",
    )
    referral_active_upline_days = fields.Integer(
        string="Active Period (Days)",
        config_parameter="omni_referral_base.active_upline_days",
        default=30,
        help="Number of days to look back when checking if an upline is active. "
             "e.g. 7 = must have a confirmed SO within the last week, 30 = last month.",
    )

    def set_values(self):
        res = super().set_values()
        prefix = (self.referral_member_code_prefix or "MEM").strip()
        seq = self.env["ir.sequence"].sudo().search(
            [("code", "=", "omni.referral.member.code")], limit=1
        )
        if seq:
            seq.write({"prefix": prefix})
        return res