from odoo import fields, models


class ResConfigSettings(models.TransientModel):
    _inherit = "res.config.settings"

    referral_member_code_prefix = fields.Char(
        string="Member Code Prefix",
        config_parameter="omni_referral_base.referral_member_code_prefix",
        default="MEM",
        help="Prefix for autogenerated Member Code sequence.",
    )

    def set_values(self):
        res = super().set_values()
        prefix = (self.referral_member_code_prefix or "MEM").strip()
        seq = self.env["ir.sequence"].sudo().search(
            [("code", "=", "omni.referral.member.code")], limit=1
        )
        if seq:
            seq.write({"prefix": prefix})
        return res